package com.therenegadecoder.poplibrary

enum class FountasAndPinell(val recommendedGrade: String) {
    A("Kindergarten"),
    B("Kindergarten"),
    C("Kindergarten"),
    D("Kindergarten"),
    E("First Grade"),
    F("First Grade"),
    G("First Grade"),
    H("First Grade"),
    I("First Grade"),
    J("First Grade"),
    K("Second Grade"),
    L("Second Grade"),
    M("Second Grade"),
    N("Third Grade"),
    O("Third Grade"),
    P("Third Grade"),
    Q("Fourth Grade"),
    R("Fourth Grade"),
    S("Fourth Grade"),
    T("Fifth Grade"),
    U("Fifth Grade"),
    V("Fifth Grade"),
    W("Sixth Grade"),
    X("Sixth Grade"),
    Y("Sixth Grade"),
    Z("Seventh and Eight Grade"),
    Z_PLUS("High School and Adult")
}